name: Deploy on server
on:
  push:
    branches:
      - main
      - 'fix-ci-cd'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: copy env file
        run: cp .env.example .env
      - name: install npm dependencies
        run: npm ci
      - name: run linter
        run: npm run lint
      - name: Deploy to Server
        if: ${{ success() }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script_stop: true
          script: |
            cd apps
            cd front-movie-quotes-tamar-sinauridze
            git pull
            npm ci
            npm run build
